import {
  SiCss3,
  SiCss3Hex,
  SiDocker,
  SiDockerHex,
  SiEslint,
  SiEslintHex,
  SiExpress,
  SiExpressHex,
  SiGit,
  SiGitHex,
  SiGithub,
  SiGithubHex,
  SiHtml5,
  SiHtml5Hex,
  SiJavascript,
  SiJavascriptHex,
  SiJest,
  SiJestHex,
  SiMobx,
  SiMobxHex,
  SiMongodb,
  SiMongodbHex,
  SiNestjs,
  SiNestjsHex,
  SiNextdotjs,
  SiNodedotjs,
  SiNodedotjsHex,
  SiNuxtdotjs,
  SiNuxtdotjsHex,
  SiPostgresql,
  SiPostgresqlHex,
  SiPrettier,
  SiPrettierHex,
  SiPrisma,
  SiPrismaHex,
  SiRadixui,
  SiReact,
  SiReactHex,
  SiRedux,
  SiReduxHex,
  SiSass,
  SiSassHex,
  SiTailwindcss,
  SiTailwindcssHex,
  SiTypescript,
  SiTypescriptHex,
  SiVite,
  SiViteHex,
  SiVitest,
  SiVitestHex,
  SiVuedotjs,
  SiVuedotjsHex,
  SiWebpack,
  SiWebpackHex
} from '@icons-pack/react-simple-icons'

export const skillsList = {
  JavaScript: <SiJavascript color={SiJavascriptHex} />,
  TypeScript: <SiTypescript color={SiTypescriptHex} />,
  React: <SiReact color={SiReactHex} />,
  'React.js': <SiReact color={SiReactHex} />,
  'Next.js': <SiNextdotjs className='text-neutral-800 dark:text-neutral-200' />,
  'Node.js': <SiNodedotjs color={SiNodedotjsHex} />,
  Express: <SiExpress color={SiExpressHex} />,
  Prisma: <SiPrisma color={SiPrismaHex} />,
  Vue: <SiVuedotjs color={SiVuedotjsHex} />,
  'Nuxt.js': <SiNuxtdotjs color={SiNuxtdotjsHex} />,
  TailwindCSS: <SiTailwindcss color={SiTailwindcssHex} />,
  Vite: <SiVite color={SiViteHex} />,
  Webpack: <SiWebpack color={SiWebpackHex} />,
  Vitest: <SiVitest color={SiVitestHex} />,
  Jest: <SiJest color={SiJestHex} />,
  'Nest.js': <SiNestjs color={SiNestjsHex} />,
  MongoDB: <SiMongodb color={SiMongodbHex} />,
  PostgreSQL: <SiPostgresql color={SiPostgresqlHex} />,
  Docker: <SiDocker color={SiDockerHex} />,
  Git: <SiGit color={SiGitHex} />,
  GitHub: <SiGithub color={SiGithubHex} />,
  Redux: <SiRedux color={SiReduxHex} />,
  MobX: <SiMobx color={SiMobxHex} />,
  // Zustand: <SiZustand />,
  CSS: <SiCss3 color={SiCss3Hex} />,
  RadixUI: <SiRadixui className='text-neutral-800 dark:text-neutral-200' />,
  HTML: <SiHtml5 color={SiHtml5Hex} />,
  Prettier: <SiPrettier color={SiPrettierHex} />,
  ESLint: <SiEslint color={SiEslintHex} />,
  SASS: <SiSass color={SiSassHex} />
  // Emotion: <SiEmotion />
}
